version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: order_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
